language: python

# using container based testing is faster, but you can't use sudo
sudo: false

python:
    - "3.6"
    - "2.7"

# install other libraries using pip
install:
    - pip install -U pip setuptools wheel
    - pip install -U -r requirements.txt
    - pip install -U .

# command to run tests
script: nosetests -v -w tests test.py
